# Generated by Django 5.2.12 on 2026-04-01 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('slug', models.SlugField(max_length=120, unique=True, verbose_name='slug')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='sort order')),
            ],
            options={
                'verbose_name': 'collection',
                'verbose_name_plural': 'collections',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('slug', models.SlugField(max_length=220, unique=True, verbose_name='slug')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('is_limited_edition', models.BooleanField(default=False, help_text='True when the limited-edition status applies to the whole design. Individual variants can also be marked limited edition independently.', verbose_name='limited edition')),
                ('dimensions_note', models.CharField(blank=True, max_length=200, verbose_name='dimensions note')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='sort order')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.collection', verbose_name='collection')),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=100, unique=True, verbose_name='SKU')),
                ('material', models.CharField(max_length=100, verbose_name='material')),
                ('color', models.CharField(max_length=100, verbose_name='color')),
                ('finish', models.CharField(blank=True, help_text='E.g. painted, hand-painted, natural finish, raw.', max_length=100, verbose_name='finish')),
                ('is_hand_painted', models.BooleanField(default=False, help_text='Explicit flag for hand-painted finish. Kept separate to allow easy filtering and display.', verbose_name='hand-painted')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='price')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='stock')),
                ('is_active', models.BooleanField(default=True, help_text='Only active variants are purchasable and shown on the storefront.', verbose_name='active')),
                ('is_limited_edition', models.BooleanField(default=False, help_text='True when limited-edition status is specific to this variant.', verbose_name='limited edition')),
                ('weight_grams', models.PositiveIntegerField(blank=True, null=True, verbose_name='weight (grams)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='variants', to='catalog.product', verbose_name='product')),
            ],
            options={
                'verbose_name': 'product variant',
                'verbose_name_plural': 'product variants',
                'ordering': ['product', 'material', 'color'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='catalog/', verbose_name='image')),
                ('alt_text', models.CharField(blank=True, max_length=200, verbose_name='alt text')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='sort order')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.product', verbose_name='product')),
                ('variant', models.ForeignKey(blank=True, help_text='Leave blank for general product imagery. Set to link this image to a specific variant.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='catalog.productvariant', verbose_name='variant')),
            ],
            options={
                'verbose_name': 'product image',
                'verbose_name_plural': 'product images',
                'ordering': ['sort_order'],
            },
        ),
    ]
