# Generated by Django 5.2.12 on 2026-04-22 08:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial_catalog_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(editable=False, help_text='Human-readable public identifier, e.g. EFF-20240001.', max_length=32, unique=True, verbose_name='order number')),
                ('reference', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='reference')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('first_name', models.CharField(max_length=100, verbose_name='first name')),
                ('last_name', models.CharField(max_length=100, verbose_name='last name')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='phone')),
                ('company_name', models.CharField(blank=True, help_text='Optional. For B2B or gift orders.', max_length=200, verbose_name='company name')),
                ('shipping_full_name', models.CharField(max_length=200, verbose_name='shipping full name')),
                ('shipping_address_line_1', models.CharField(max_length=200, verbose_name='shipping address line 1')),
                ('shipping_address_line_2', models.CharField(blank=True, max_length=200, verbose_name='shipping address line 2')),
                ('shipping_postal_code', models.CharField(max_length=20, verbose_name='shipping postal code')),
                ('shipping_city', models.CharField(max_length=100, verbose_name='shipping city')),
                ('shipping_region', models.CharField(blank=True, help_text='Province or state. Optional for most EU addresses.', max_length=100, verbose_name='shipping region / state')),
                ('shipping_country', models.CharField(help_text='ISO 3166-1 alpha-2 country code.', max_length=2, verbose_name='shipping country')),
                ('shipping_phone', models.CharField(blank=True, max_length=30, verbose_name='shipping phone')),
                ('billing_same_as_shipping', models.BooleanField(default=True, verbose_name='billing same as shipping')),
                ('billing_full_name', models.CharField(blank=True, max_length=200, verbose_name='billing full name')),
                ('billing_address_line_1', models.CharField(blank=True, max_length=200, verbose_name='billing address line 1')),
                ('billing_address_line_2', models.CharField(blank=True, max_length=200, verbose_name='billing address line 2')),
                ('billing_postal_code', models.CharField(blank=True, max_length=20, verbose_name='billing postal code')),
                ('billing_city', models.CharField(blank=True, max_length=100, verbose_name='billing city')),
                ('billing_region', models.CharField(blank=True, max_length=100, verbose_name='billing region / state')),
                ('billing_country', models.CharField(blank=True, max_length=2, verbose_name='billing country')),
                ('currency', models.CharField(default='EUR', help_text='ISO 4217. EUR only at launch.', max_length=3, verbose_name='currency')),
                ('subtotal', models.DecimalField(decimal_places=2, help_text='Sum of order item line totals before shipping.', max_digits=10, verbose_name='subtotal')),
                ('shipping_total', models.DecimalField(decimal_places=2, help_text='Flat shipping fee applied at time of order.', max_digits=8, verbose_name='shipping total')),
                ('grand_total', models.DecimalField(decimal_places=2, help_text='subtotal + shipping_total. Frozen at time of order.', max_digits=10, verbose_name='grand total')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('pending_payment', 'Pending payment'), ('paid', 'Paid'), ('fulfilled', 'Fulfilled / Shipped'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='pending', max_length=20, verbose_name='status')),
                ('customer_note', models.TextField(blank=True, help_text='Optional note from the customer at checkout.', verbose_name='customer note')),
                ('placed_at', models.DateTimeField(auto_now_add=True, verbose_name='placed at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'order',
                'verbose_name_plural': 'orders',
                'ordering': ['-placed_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(help_text='Snapshot of product name at time of purchase.', max_length=200, verbose_name='product name')),
                ('variant_sku', models.CharField(help_text='Snapshot of variant SKU at time of purchase.', max_length=100, verbose_name='SKU')),
                ('variant_material', models.CharField(help_text='Snapshot of variant material at time of purchase.', max_length=100, verbose_name='material')),
                ('variant_color', models.CharField(help_text='Snapshot of variant color at time of purchase.', max_length=100, verbose_name='color')),
                ('variant_finish', models.CharField(blank=True, help_text='Snapshot of variant finish at time of purchase.', max_length=100, verbose_name='finish')),
                ('variant_description', models.CharField(help_text='Snapshot of full variant display string at time of purchase.', max_length=500, verbose_name='variant description')),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Price per unit at time of purchase, in order currency.', max_digits=8, verbose_name='unit price')),
                ('quantity', models.PositiveIntegerField(verbose_name='quantity')),
                ('line_total', models.DecimalField(decimal_places=2, help_text='unit_price × quantity. Stored, not recalculated.', max_digits=10, verbose_name='line total')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='orders.order', verbose_name='order')),
                ('product_ref', models.ForeignKey(blank=True, help_text='Nullable FK for traceability. Do not use as authoritative — use snapshot fields.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='catalog.product', verbose_name='product (ref)')),
                ('variant_ref', models.ForeignKey(blank=True, help_text='Nullable FK for traceability. Do not use as authoritative — use snapshot fields.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='catalog.productvariant', verbose_name='variant (ref)')),
            ],
            options={
                'verbose_name': 'order item',
                'verbose_name_plural': 'order items',
                'ordering': ['pk'],
            },
        ),
    ]
