# Generated by Django 5.2.12 on 2026-05-03 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='reservation_expires_at',
            field=models.DateTimeField(blank=True, help_text='When the stock reservation for this order lapses if no successful payment is recorded. Cleared once the order reaches a terminal state.', null=True, verbose_name='reservation expires at'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('pending_payment', 'Pending payment'), ('paid', 'Paid'), ('fulfilled', 'Fulfilled / Shipped'), ('payment_failed', 'Payment failed'), ('expired', 'Expired'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='pending', max_length=20, verbose_name='status'),
        ),
    ]
