# Generated by Django 5.2.12 on 2026-05-03 10:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0002_order_reservation_expires_at_alter_order_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(default='mollie', help_text="PSP identifier. MVP only uses 'mollie'.", max_length=32, verbose_name='provider')),
                ('provider_payment_id', models.CharField(blank=True, help_text='Reference returned by the PSP after creating the payment.', max_length=128, verbose_name='provider payment id')),
                ('checkout_url', models.URLField(blank=True, help_text='Hosted checkout URL returned by the PSP. UX-only; never used as truth.', max_length=500, verbose_name='checkout URL')),
                ('amount_cents', models.PositiveIntegerField(help_text='Integer cents to avoid floating-point issues. EUR for MVP.', verbose_name='amount in cents')),
                ('currency', models.CharField(default='EUR', help_text='ISO 4217. EUR only at launch.', max_length=3, verbose_name='currency')),
                ('status', models.CharField(choices=[('created', 'Created'), ('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('expired', 'Expired'), ('refunded', 'Refunded')], default='created', max_length=16, verbose_name='status')),
                ('idempotency_key', models.CharField(blank=True, help_text="Sent to the PSP's create-payment call so retries do not duplicate.", max_length=64, verbose_name='idempotency key')),
                ('raw_provider_payload_last', models.JSONField(blank=True, default=dict, help_text='Last raw provider payload observed for this payment, for audit/debug.', verbose_name='raw provider payload (last)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='orders.order', verbose_name='order')),
            ],
            options={
                'verbose_name': 'payment',
                'verbose_name_plural': 'payments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider_refund_id', models.CharField(blank=True, help_text='Reference returned by the PSP after creating the refund.', max_length=128, verbose_name='provider refund id')),
                ('amount_cents', models.PositiveIntegerField(help_text='Must equal order.grand_total (in cents) for MVP — full refund only.', verbose_name='amount in cents')),
                ('currency', models.CharField(default='EUR', max_length=3, verbose_name='currency')),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('processing', 'Processing'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='requested', max_length=16, verbose_name='status')),
                ('idempotency_key', models.CharField(blank=True, help_text="Sent to the PSP's refund call so retries do not duplicate.", max_length=64, verbose_name='idempotency key')),
                ('raw_provider_payload_last', models.JSONField(blank=True, default=dict, verbose_name='raw provider payload (last)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('created_by', models.ForeignKey(blank=True, help_text='Staff user who triggered the refund.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_refunds', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='orders.order', verbose_name='order')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='payments.payment', verbose_name='payment')),
            ],
            options={
                'verbose_name': 'refund',
                'verbose_name_plural': 'refunds',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(default='mollie', max_length=32, verbose_name='provider')),
                ('provider_event_key', models.CharField(help_text='Unique key per delivery used for dedup. For Mollie this is typically the provider payment id reported in the webhook body.', max_length=255, verbose_name='provider event key')),
                ('payload', models.JSONField(blank=True, default=dict, help_text='Raw inbound payload as received.', verbose_name='payload')),
                ('received_at', models.DateTimeField(auto_now_add=True, verbose_name='received at')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='processed at')),
                ('processing_status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=16, verbose_name='processing status')),
                ('processing_error', models.TextField(blank=True, help_text='Error message if processing_status is failed.', verbose_name='processing error')),
            ],
            options={
                'verbose_name': 'webhook event',
                'verbose_name_plural': 'webhook events',
                'ordering': ['-received_at'],
                'constraints': [models.UniqueConstraint(fields=('provider', 'provider_event_key'), name='unique_provider_event_key')],
            },
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['provider', 'provider_payment_id'], name='payments_pa_provide_3e1786_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['order', 'status'], name='payments_pa_order_i_a76289_idx'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(condition=models.Q(('provider_payment_id', ''), _negated=True), fields=('provider', 'provider_payment_id'), name='unique_provider_payment_id'),
        ),
        migrations.AddConstraint(
            model_name='refund',
            constraint=models.UniqueConstraint(condition=models.Q(('provider_refund_id', ''), _negated=True), fields=('payment', 'provider_refund_id'), name='unique_payment_provider_refund_id'),
        ),
    ]
